### ISSUE TITLE
Nodelet managers in sensing_launch

### ISSUE THREAD

**Issue by fred-apex-ai** [tier4/autoware_launcher.iv.universe#21]
Does anyone know if in `sensing_launch`, the data from one velodyne were preprocessed separately in one nodelet container, and then aggregated from multiple lidars in a separate nodelet manager? The default values of the manager name imply that but I don't know if they were ever overridden from the command line. 

Taking `aip_s1` as an example, in https://github.com/tier4/autoware_launcher.iv.universe/blob/master/sensing_launch/launch/aip_s1/lidar.launch#L8

      <include file="$(find sensing_launch)/launch/velodyne_VLS128.launch">
    
and in that file 
https://github.com/tier4/autoware_launcher.iv.universe/blob/master/sensing_launch/launch/velodyne_VLS128.launch#L11

    <arg name="manager" default="velodyne_nodelet_manager" />

But later in
https://github.com/tier4/autoware_launcher.iv.universe/blob/master/sensing_launch/launch/aip_s1/lidar.launch#L36, this name is used for the agreggate nodelet manager 

    <arg name="manager" default="lidar_nodelet_manager" />
    
If somebody invoked `lidar.launch` with `manager:=velodyne_nodelet_manager`, then they previously were in the same process. But now since I have to create the container of composable nodes in python, I would need to add lots of extra logic to support this edge case, otherwise I can just have two separate python files and it's more straightforward

**Comment by mitsudome-r** [comment]
`sensing_launch` is meant to be called from `autoware.launch` in general when we launch in an actual vehicle, and since it doesn't call `sensing_launch` with the `manager` argument, I think it is okay to keep the containers separately. https://github.com/tier4/autoware_launcher.iv.universe/blob/038ff4f7a7c7b98ad333089319c94845d2202973/autoware_launch/launch/autoware.launch#L30

Therefore, if there are two lidars in `lidar.launch` there should be three containers as shown in the diagram.
<img src=https://user-images.githubusercontent.com/43976834/100862623-ba68ad00-34d6-11eb-8c37-78dcfb8adb33.png width=400>

**Comment by fred-apex-ai** [comment]
@mitsudome-r thanks a lot for the great explanation, that's what I thought and now I can continue
